export enum FileStatus {
    INITIALIZED = 'INITIALIZED',
    UPLOADING = 'UPLOADING',
    UPLOADED = 'UPLOADED',
    READY_FOR_CHECKSUM = 'READY_FOR_CHECKSUM',
    READY_FOR_ARCHIVE = 'READY_FOR_ARCHIVE',
    MARK_FOR_DELETION = 'MARK_FOR_DELETION'
}
