sudo: required
dist: trusty
language: node_js
node_js:
  - "8.7.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - npm install -g karma
  - npm install
  - ng build --prod --base-href "https://embl-ebi-subs.github.io/data-submissions-interface/"

script:
  - karma start karma.conf.js --single-run

after_success:
  - angular-cli-ghpages --repo=https://GH_TOKEN@github.com/EMBL-EBI-SUBS/data-submissions-interface.git  --no-silent

notifications:
  email:
    on_failure: change
    on_success: change
