sudo: required
dist: trusty
language: node_js
node_js:
  - "10.11.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master
    - develop

before_script:
  - npm install
  - npm run build:dev

script:
  - npm run test

notifications:
  email:
    on_failure: change
    on_success: change
