sudo: required
dist: trusty
language: node_js
node_js:
  - "10.11.0"

addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
      - google-chrome-beta

branches:
  only:
    - master
    - develop

before_script:
  - npm run build:prod

script:
  - npm run lint
  - npm run test:chromium

notifications:
  email:
    on_failure: change
    on_success: change
